// Generated by CoffeeScript 1.10.0
(function() {
  var log, output_colored;

  output_colored = function(color_code, type, message) {
    return console.log('%s\x1b[' + color_code + 'm%s\x1b[0m%s%s', '[', type, '] ', message);
  };

  log = {
    debug: function(message) {
      return output_colored(34, 'debug', message);
    },
    info: function(message) {
      return output_colored(36, 'info', message);
    },
    success: function(message) {
      return output_colored(32, ' ok ', message);
    },
    warn: function(message) {
      return output_colored(33, 'warn', message);
    },
    error: function(message) {
      return output_colored(31, 'error', message);
    }
  };

  module.exports = log;

}).call(this);
