// Generated by CoffeeScript 1.10.0
(function() {
  var exec, installDependencies, log, setConfig, sys;

  sys = require('sys');

  exec = require('child_process').exec;

  log = {
    info: function(message) {
      return console.log('%s\x1b[36m%s\x1b[0m%s%s', '[', 'info', '] ', message);
    },
    success: function(message) {
      return console.log('%s\x1b[32m%s\x1b[0m%s%s', '[', ' ok ', '] ', message);
    },
    warn: function(message) {
      return console.log('%s\x1b[33m%s\x1b[0m%s%s', '[', 'warn', '] ', message);
    },
    error: function(message) {
      return console.log('%s\x1b[31m%s\x1b[0m%s%s', '[', 'error', '] ', message);
    }
  };

  log.info('Minecraft Market installer');

  installDependencies = function(callback) {
    var child;
    log.info('Installing dependencies... (this may take a while and requires an internet connection)');
    return child = exec('npm install', function(err, stdout, stderr) {
      if (err != null) {
        return log.erorr('An error occurred trying to install dependencies, make sure you have npm installed');
      } else {
        log.success('Dependencies installed');
        return callback();
      }
    });
  };

  setConfig = function(callback) {
    log.warn('-----------------------------------------------------------------------');
    log.warn('** IMPORTANT ** Please edit the config.json to use the correct settings');
    return log.warn('-----------------------------------------------------------------------');
  };

  installDependencies(setConfig);

}).call(this);
