// Generated by CoffeeScript 1.10.0
var createDirectories, exec, installDependencies, log, next, performInstallation, setConfig, sys;

log = require('./simple-logger');

sys = require('sys');

exec = require('child_process').exec;

log.info('Minecraft Market installer');

installDependencies = function(callback) {
  var child;
  log.info('Installing dependencies... (this may take a while and requires an internet connection)');
  return child = exec('npm install', function(err, stdout, stderr) {
    if (err != null) {
      return log.erorr('An error occurred trying to install dependencies, make sure you have npm installed');
    } else {
      log.success('Dependencies installed');
      return callback();
    }
  });
};

createDirectories = function(callback) {
  var async, createDirectory, fs, required_directories;
  fs = require('fs-extra');
  async = require('async');
  required_directories = ['logs', 'user-content/item-images'];
  createDirectory = function(directory, callback) {
    return fs.ensureDir(directory, function(err) {
      if (err != null) {
        log.error(err);
      }
      return callback();
    });
  };
  return async.each(required_directories, createDirectory, function() {
    log.info('Created required directories');
    return callback();
  });
};

setConfig = function(callback) {
  log.warn('-----------------------------------------------------------------------');
  log.warn('** IMPORTANT ** Please edit the config.json to use the correct settings');
  return log.warn('-----------------------------------------------------------------------');
};

next = function() {
  var async;
  async = require('async');
  return async.series([createDirectories, setConfig]);
};

performInstallation = function() {
  return installDependencies(next);
};

module.exports.install = performInstallation;

performInstallation();
