// Generated by CoffeeScript 1.10.0
(function() {
  var start;

  start = function(ready) {
    var app, bodyParser, config, express, flash, getLogger, loadServerConfig, logger, server_properties;
    config = require('./config.json');
    getLogger = function(name, level) {
      var log4js, logger;
      log4js = require('log4js');
      log4js.configure({
        appenders: [
          {
            type: 'console'
          }, {
            type: 'file',
            filename: 'logs/' + config.logger.filename,
            category: name
          }
        ]
      });
      logger = log4js.getLogger(name);
      logger.setLevel(level);
      return logger;
    };
    logger = getLogger('market-web', config.logger.level);
    server_properties = {};
    loadServerConfig = function() {
      var request;
      request = require('request');
      return request.get(config.hostname, function(err, res, body) {
        if (typeof error === "undefined" || error === null) {
          return JSON.parse(body);
        }
      });
    };
    express = require('express');
    app = express();
    bodyParser = require('body-parser');
    app.use(bodyParser.json({
      limit: '5mb'
    }));
    app.use(bodyParser.json({
      limit: '5mb',
      extended: true
    }));
    flash = require('connect-flash');
    app.use(flash());
    app.use('/static', express["static"]('webcontent'));
    app.get('/signin', function(req, res) {
      if (!signed_in) {
        return res.render('signin.jade', {
          message: req.flash('error')
        });
      } else {
        return res.redirect('/');
      }
    });
    app.get('/', function(req, res) {
      if (signed_in) {
        res.render('index.jade');
      } else {
        res.redirect('/signin');
      }
      return res.render('index.jade');
    });
    return app.get('/jade/:name', function(req, res) {
      if (signed_in) {
        return res.render(req.params.name, {
          title: market_title,
          bankid: req.user.bankid
        });
      } else {
        return res.redirect('/signin');
      }
    });
  };

  module.exports.start = start;

}).call(this);
