// Generated by CoffeeScript 1.10.0
(function() {
  var async, current_package, current_version, getLatestPackageInfo, installNewVersion, log, newest_version;

  log = require('./modules/simple-logger');

  async = require('async');

  current_package = require('./package.json');

  current_version = current_package.version;

  log.info('Current version is ' + current_version);

  newest_version = '';

  getLatestPackageInfo = function(callback) {
    var https, request;
    https = require('https');
    log.info('Fetching package info about the latest version...');
    request = https.get('https://raw.githubusercontent.com/nicolaschan/market/master/package.json', function(res) {
      var body;
      body = '';
      res.on('data', function(chunk) {
        return body += chunk;
      });
      return res.on('end', function() {
        log.success('Package info fetched');
        return callback(JSON.parse(body));
      });
    });
    return request.on('error', function(err) {
      return log.error(err);
    });
  };

  installNewVersion = function(callback) {
    var createTempDirectory, deleteTempDirectory, download, exec, fs, https, installDependencies, moveOldConfig, path, replaceFiles, temp_directory, zip_file_path;
    log.info('Updating...');
    https = require('https');
    fs = require('fs-extra');
    path = require('path');
    exec = require('child_process').exec;
    temp_directory = __dirname + path.sep + 'temp';
    zip_file_path = temp_directory + path.sep + 'market.zip';
    createTempDirectory = function(callback) {
      if (!fs.existsSync(temp_directory)) {
        log.info('Creating temp directory...');
        fs.mkdirSync(temp_directory);
      }
      return callback();
    };
    download = function(callback) {
      return exec('git clone https://github.com/nicolaschan/market.git ' + temp_directory, function(err, stdout, stderr) {
        if (err != null) {
          return log.erorr('An error occurred trying to download the latest version, make sure you have git installed');
        } else {
          log.success('New version downloaded');
          return callback();
        }
      });
    };
    moveOldConfig = function(callback) {
      var new_config_path, old_config_path;
      log.info('Moving config.json...');
      old_config_path = __dirname + path.sep + 'config.json';
      new_config_path = __dirname + path.sep + 'config-' + current_version + '.json';
      return fs.rename(old_config_path, new_config_path, function(err) {
        if (err != null) {
          log.error(err);
        } else {
          log.success('The old config file has been moved to ' + new_config_path);
          log.warn('You will need to update the new config.json!');
        }
        return callback();
      });
    };
    replaceFiles = function(callback) {
      var new_market_directory, replaceFile;
      new_market_directory = temp_directory;
      replaceFile = function(filename, callback) {
        var deleteFile, done, file_path, moveFile;
        done = 0;
        file_path = new_market_directory + path.sep + filename;
        deleteFile = function(callback) {
          return fs.remove(__dirname + path.sep + filename, function(err) {
            log.debug(__dirname + path.sep + filename + ' deleted');
            if (err != null) {
              log.error(err);
            }
            return callback();
          });
        };
        moveFile = function(callback) {
          return fs.move(file_path, __dirname + path.sep + filename, function(err) {
            log.debug(file_path + ' moved');
            if (err != null) {
              log.error(err);
            }
            return callback();
          });
        };
        return async.series([deleteFile, moveFile, callback]);
      };
      log.info('Replacing old files with the new ones...');
      return fs.readdir(new_market_directory, function(err, files) {
        if (err != null) {
          log.error(err);
        }
        return async.each(files, replaceFile, function() {
          log.success('Done replacing files');
          return callback();
        });
      });
    };
    deleteTempDirectory = function(callback) {
      var escapeSpaces;
      log.info('Deleting temp folder...');
      escapeSpaces = function(string) {
        var addToOutput, i, len, output, piece, pieces, ref;
        pieces = string.split(' ');
        output = pieces[0];
        addToOutput = function(piece) {
          return output += '\\ ' + piece;
        };
        ref = pieces.slice(1);
        for (i = 0, len = ref.length; i < len; i++) {
          piece = ref[i];
          addToOutput(piece);
        }
        return output;
      };
      return fs.remove(temp_directory, function(err) {
        if (err != null) {
          log.error(err);
        }
        return callback();
      });
    };
    installDependencies = function(callback) {
      var child;
      log.info('Installing dependencies... (this may take a while and requires an internet connection)');
      return child = exec('npm install', function(err, stdout, stderr) {
        if (err != null) {
          return log.erorr('An error occurred trying to install dependencies, make sure you have npm installed');
        } else {
          log.success('Dependencies installed');
          return callback();
        }
      });
    };
    return async.series([createTempDirectory, download, moveOldConfig, replaceFiles, deleteTempDirectory, installDependencies]);
  };

  getLatestPackageInfo(function(latest_package) {
    newest_version = latest_package.version;
    log.info('Newest available version is ' + newest_version);
    if (current_version !== newest_version) {
      log.info('Update is required, updating now...');
      return installNewVersion();
    } else {
      log.success('Current installation is up to date!');
      return log.success('This market installation is up to date');
    }
  });

}).call(this);
